c_compiler_version:
  - 7.2.0                      # [x86_64]
  - 7.3.0                      # [ppc64le]
cxx_compiler_version:
  - 7.2.0                      # [x86_64]
  - 7.3.0                      # [ppc64le]
